[Pins]
# IN2
right_forward = 18
# IN1
right_backward = 22
# IN4
left_forward = 15
# IN3
left_backward = 16
enA = 11
enB = 13

[PWM]
# This should be where the motor starts to "bite"
minimum_motor_PWM = 20
maximum_motor_PWM  = 60

[Car.handling.commands]
turn_left = turn left
turn_right = turn right
drive = go forward
reverse = go backward
stop = stop now
increase_speed = go faster
decrease_speed = go slower

# add {param} for where in command to add the speed value
exact_speed = speed {param}

[Other]
# how much the speed should change when you give command to increase or decrease speed
speed_step = 10