user_controller: "keyboard"

logging:
  level:
    main: "info"

audio:
  commands:
    exit: "cancel program"

xbox:
  commands:
    # this needs to be a push button
    exit: "Back"

keyboard:
  commands:
    exit: "esc"