user_controller: "keyboard"

logging:
  level:
    main: "info"
    command_handler: "debug"
    stabilizer: "info"
    camera: "error"
  timezone: "Europe/Oslo"

audio:
  commands:
    exit: "cancel program"

xbox:
  commands:
    # this needs to be a push button
    exit: "Back"

keyboard:
  commands:
    exit: "esc"