user_controller: "xbox"
signal_lights:
  enabled:
    false # keeping these on can slow down command handling

audio:
  commands:
    exit: "cancel program"

xbox:
  commands:
    # this needs to be a push button
    exit: "Back"