Pin:
  pin: 36

Honk_times:
  default_honk_time: 0.3
  max_honk_time: 2

audio:
  commands:
    # command to honk for the default amount of time
    honk: "start horn"
    # add {param} for where in command to add the specified time
    honk_for_specified_time: "start horn {param}"

  command_descriptions:
    honk: "Starts honking"
    honk_for_specified_time: "Honks for the specified time"

xbox:
  commands:
    honk: "X"

  command_descriptions:
    honk: "Honks while button is pressed"