[Car.handling.specs]
# IN2
right_forward = 18
# IN1
right_backward = 22
# IN4
left_forward = 15
# IN3
left_backward = 16
enA = 11
enB = 13

# This should be where the motor starts to "bite"
minimum_motor_PWM = 20
maximum_motor_PWM  = 60

# how much the speed should change when you give command to increase or decrease speed
speed_step = 10

[Car.handling.commands]
turn_left = turn left
turn_right = turn right
drive = go forward
reverse = go backward
stop = stop now
increase_speed = go faster
decrease_speed = go slower

# add {param} for where in command to add the speed value
exact_speed = speed {param}


[Audio.specs]
language = English (United States)
microphone_name = WH-1000XM3

[Stabilizer]
pitch_axis = x
roll_axis = y
roll_treshold = 3
pitch_treshold = 3
offset_x = 2.32
offset_y = -1.24

[Stabilizer.servo.channels]
# give the channel numbers for the stabilizer servo motors
front_right = 0
front_left = 2
rear_right = 3
rear_left = 1

[Global.commands]
exit = cancel program

[Start.button]
pin = 38

[Repo.path]
# where you've cloned the repository
path = /home/christian/GIT